[package]
name = "abusd"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "D-Bus broker daemon"
authors.workspace = true
repository.workspace = true
keywords.workspace = true
categories = ["os::unix-apis"]
license = "EUPL-1.2"
readme = "README.md"
include = ["src/**/*.rs", "README.md", "LICENSE"]

[[bin]]
name = "abusd"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "signal"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
