// SPDX-License-Identifier: Apache-2.0
use abus_xml::Node;
use anyhow::{Context, Result, bail};
use sap::{Argument, Parser};

const USAGE: &str = "\
Generate Rust code from a D-Bus introspection XML file.

Options:
  -h, --help    Print this help message";

fn usage(name: &str) {
    eprintln!("Usage: {name} [options] <FILE>\n\n{USAGE}");
}

fn main() -> Result<()> {
    let mut parser = Parser::from_env()?;
    let name = parser.name().to_owned();

    let mut input: Option<String> = None;

    while let Some(arg) = parser.forward()? {
        match arg {
            Argument::Short('h') | Argument::Long("help") => {
                usage(&name);
                return Ok(());
            }
            Argument::Value(_) if input.is_some() => bail!("Only one input file is supported"),
            Argument::Value(val) => input = Some(val.into_owned()),
            Argument::Short(c) => bail!("Unknown flag: -{c}"),
            Argument::Long(s) => bail!("Unknown flag: --{s}"),
            Argument::Stdio => bail!("Reading from stdin is not supported"),
        }
    }

    let Some(path) = input else {
        usage(&name);
        std::process::exit(1);
    };

    let xml = std::fs::read_to_string(&path).with_context(|| format!("failed to read {path}"))?;
    let node = Node::from_xml(&xml).context("failed to parse introspection XML")?;

    print!("{}", generate(&node));

    Ok(())
}

/// Placeholder until real code generation exists: emits a summary of the parsed XML as comments.
fn generate(node: &Node) -> String {
    let mut out = String::from("// Generated by abus-xml. Code generation is not implemented yet.\n");

    for iface in &node.interfaces {
        out.push_str(&format!(
            "// interface {}: {} methods, {} signals, {} properties\n",
            iface.name,
            iface.methods.len(),
            iface.signals.len(),
            iface.properties.len(),
        ));
    }

    out
}
